import type { GlossaryEntry } from "../types";

export const glossary: GlossaryEntry[] = [
  {
    slug: "cognitive-triad",
    termZh: "認知三角",
    termEn: "Cognitive triad",
    category: "cognition",
    definition:
      "Beck 憂鬱模型中對自我、世界（經驗）與未來的系統性負向觀，常與基模及自動思考一併評估。",
    related: ["automatic-thought", "schema", "cbt"],
  },
  {
    slug: "automatic-thought",
    termZh: "自動思考",
    termEn: "Automatic thought",
    category: "therapy",
    definition: "情境中快速、往往未被檢視的念頭，是認知治療初期最常捕捉的材料。",
    related: ["cognitive-triad", "cognitive-restructuring"],
  },
  {
    slug: "schema",
    termZh: "基模／核心信念",
    termEn: "Schema / core belief",
    category: "cognition",
    definition: "高度概括、通常早年形成的自我—世界信念，會組織注意、記憶與解釋。",
    related: ["cognitive-triad", "case-formulation"],
  },
  {
    slug: "working-memory",
    termZh: "工作記憶",
    termEn: "Working memory",
    category: "cognition",
    definition: "短暫維持並操作資訊的系統，極度依賴注意力與執行控制，易受憂鬱、焦慮與睡眠影響。",
    related: ["executive-function", "attention"],
  },
  {
    slug: "executive-function",
    termZh: "執行功能",
    termEn: "Executive function",
    category: "cognition",
    definition: "目標導向的控制過程，常被分析為抑制、心智轉換與工作記憶更新。",
    related: ["working-memory", "inhibition"],
  },
  {
    slug: "attention",
    termZh: "注意力",
    termEn: "Attention",
    category: "cognition",
    definition: "對感覺與內在訊息的選擇、維持與控制；包含警覺、定向與執行控制等可分離成分。",
    related: ["working-memory", "threat-appraisal"],
  },
  {
    slug: "inhibition",
    termZh: "抑制",
    termEn: "Inhibition",
    category: "cognition",
    definition: "壓制優勢反應或無關訊息的能力，是執行功能的核心成分之一。",
    related: ["executive-function"],
  },
  {
    slug: "threat-appraisal",
    termZh: "威脅評估",
    termEn: "Threat appraisal",
    category: "cognition",
    definition: "對刺激之危險性、發生機率與自身可應對性的估計；高估威脅會驅動焦慮與安全行為。",
    related: ["safety-behavior", "exposure"],
  },
  {
    slug: "safety-behavior",
    termZh: "安全行為",
    termEn: "Safety behavior",
    category: "therapy",
    definition: "用以防止災難發生或被發現的行為或心智動作，常阻斷新的安全學習。",
    related: ["threat-appraisal", "exposure"],
  },
  {
    slug: "exposure",
    termZh: "暴露",
    termEn: "Exposure",
    category: "therapy",
    definition: "系統性接觸引發焦慮的刺激，以修正威脅預期；當代強調抑制學習而非僅習慣化。",
    related: ["safety-behavior", "inhibitory-learning"],
  },
  {
    slug: "inhibitory-learning",
    termZh: "抑制學習",
    termEn: "Inhibitory learning",
    category: "therapy",
    definition: "暴露治療的學習觀點：新的「安全」聯結抑制舊的威脅聯結，而非把舊學習抹掉。",
    related: ["exposure", "neuroplasticity"],
  },
  {
    slug: "cognitive-restructuring",
    termZh: "認知重組",
    termEn: "Cognitive restructuring",
    category: "therapy",
    definition: "檢視並調整失衡解釋的一套技術，包括證據檢驗、替代解釋與去災難化。",
    related: ["automatic-thought", "cbt"],
  },
  {
    slug: "cbt",
    termZh: "認知行為治療",
    termEn: "Cognitive behavioral therapy",
    abbr: "CBT",
    category: "therapy",
    definition: "以學習理論與訊息處理為基礎、強調概念化、家庭作業與行為實驗的結構性心理治療。",
    related: ["cognitive-restructuring", "case-formulation"],
  },
  {
    slug: "dbt",
    termZh: "辯證行為治療",
    termEn: "Dialectical behavior therapy",
    abbr: "DBT",
    category: "therapy",
    definition: "結合接納與改變的治療，含技能訓練、個別治療、電話教練與治療師諮詢團隊。",
    related: ["emotion-regulation", "distress-tolerance"],
  },
  {
    slug: "emdr",
    termZh: "眼動脫敏與歷程處理",
    termEn: "Eye movement desensitization and reprocessing",
    abbr: "EMDR",
    category: "therapy",
    definition: "以適應性訊息處理模型為基礎、結合雙側刺激的創傷記憶再處理治療。",
    related: ["aip", "ptsd"],
  },
  {
    slug: "act",
    termZh: "接受與承諾治療",
    termEn: "Acceptance and commitment therapy",
    abbr: "ACT",
    category: "therapy",
    definition: "以心理彈性為目標的脈絡行為治療，強調接納、解離、價值與承諾行動。",
    related: ["psychological-flexibility", "defusion"],
  },
  {
    slug: "aip",
    termZh: "適應性訊息處理",
    termEn: "Adaptive information processing",
    abbr: "AIP",
    category: "therapy",
    definition: "EMDR 的理論框架，主張創傷記憶可能以未消化形式儲存並持續驅動症狀。",
    related: ["emdr"],
  },
  {
    slug: "psychological-flexibility",
    termZh: "心理彈性",
    termEn: "Psychological flexibility",
    category: "therapy",
    definition: "在此時此地接觸當下、帶著私密經驗、依價值行動的能力；ACT 的核心結果。",
    related: ["act", "defusion"],
  },
  {
    slug: "defusion",
    termZh: "認知解離",
    termEn: "Cognitive defusion",
    category: "therapy",
    definition: "改變人與念頭的關係，使語言內容不再被當成必須服從的字面真實。",
    related: ["act", "automatic-thought"],
  },
  {
    slug: "emotion-regulation",
    termZh: "情緒調節",
    termEn: "Emotion regulation",
    category: "therapy",
    definition: "影響情緒發生、強度、持續與表達的過程；DBT 以技能方式直接訓練。",
    related: ["dbt", "distress-tolerance"],
  },
  {
    slug: "distress-tolerance",
    termZh: "痛苦耐受",
    termEn: "Distress tolerance",
    category: "therapy",
    definition: "在無法立即解決問題時，不透過傷害行為撐過高峰痛苦的技能組。",
    related: ["dbt", "emotion-regulation"],
  },
  {
    slug: "case-formulation",
    termZh: "個案概念化",
    termEn: "Case formulation",
    category: "methods",
    definition: "把易感、誘發、維持與保護因子整合成可檢驗假說，用以選擇介入順序。",
    related: ["cbt", "functional-analysis"],
  },
  {
    slug: "functional-analysis",
    termZh: "功能分析",
    termEn: "Functional analysis",
    category: "methods",
    definition: "分析行為的前事、行為本身與後果，找出維持問題行為的增強關係。",
    related: ["case-formulation", "dbt"],
  },
  {
    slug: "neurodiversity",
    termZh: "神經多樣性",
    termEn: "Neurodiversity",
    category: "cognition",
    definition: "主張人腦在注意、感覺與社交等面向的變異是族群事實，臨床上需同時看見特質與損害。",
    related: ["adhd", "executive-function"],
  },
  {
    slug: "nosology",
    termZh: "疾病分類學",
    termEn: "Nosology",
    category: "psychiatry",
    definition: "疾患如何被命名與分界的系統。DSM 與 ICD 是溝通公約，不等于腦機轉地圖。",
    related: ["dsm", "icd"],
  },
  {
    slug: "dsm",
    termZh: "精神疾病診斷與統計手冊",
    termEn: "Diagnostic and Statistical Manual of Mental Disorders",
    abbr: "DSM-5-TR",
    category: "psychiatry",
    definition: "美國精神醫學學會的分類系統；TR 版本補充病程、文化與臨床文字，不取代官方準則文本。",
    related: ["icd", "nosology"],
  },
  {
    slug: "icd",
    termZh: "國際疾病分類",
    termEn: "International Classification of Diseases",
    abbr: "ICD-11",
    category: "psychiatry",
    definition: "WHO 的國際分類，廣泛用於統計、給付與健康資訊，精神單元與 DSM 並非一一對譯。",
    related: ["dsm", "nosology"],
  },
  {
    slug: "receptor-binding-profile",
    termZh: "受體結合特性",
    termEn: "Receptor binding profile",
    category: "pharmacology",
    definition: "藥物對受體／轉運體的親和與作用型態組合，常用來解釋療效與副作用剖面。",
    related: ["ssri", "d2"],
  },
  {
    slug: "ssri",
    termZh: "選擇性血清素再回收抑制劑",
    termEn: "Selective serotonin reuptake inhibitor",
    abbr: "SSRI",
    category: "pharmacology",
    definition: "以抑制 SERT 為主的抗憂鬱／抗焦慮藥物類別，次要受體差異仍會影響耐受性。",
    related: ["sert", "serotonin-syndrome"],
  },
  {
    slug: "sert",
    termZh: "血清素轉運體",
    termEn: "Serotonin transporter",
    abbr: "SERT",
    category: "pharmacology",
    definition: "負責將血清素再回收入突觸前神經元的蛋白，是 SSRI 的主要藥理標的。",
    related: ["ssri"],
  },
  {
    slug: "d2",
    termZh: "多巴胺 D2 受體",
    termEn: "Dopamine D2 receptor",
    category: "pharmacology",
    definition: "抗精神病藥療效與 EPS、泌乳素變化高度相關的受體；部分藥物為部分促效。",
    related: ["eps", "nms"],
  },
  {
    slug: "cyp450",
    termZh: "細胞色素 P450",
    termEn: "Cytochrome P450",
    abbr: "CYP450",
    category: "pharmacology",
    definition: "參與第一期藥物代謝的酶家族；誘導與抑制是精神藥物交互作用的常見機制。",
    related: ["half-life", "ddi"],
  },
  {
    slug: "ddi",
    termZh: "藥物交互作用",
    termEn: "Drug-drug interaction",
    abbr: "DDI",
    category: "pharmacology",
    definition: "一藥物改變另一藥物的暴露或藥效，可能來自 PK（代謝）或 PD（受體層）途徑。",
    related: ["cyp450", "half-life"],
  },
  {
    slug: "half-life",
    termZh: "半衰期",
    termEn: "Half-life",
    category: "pharmacology",
    definition: "血中濃度下降一半所需時間，影響達穩態、漏服後果與停藥症候群的時間表。",
    related: ["cyp450"],
  },
  {
    slug: "serotonin-syndrome",
    termZh: "血清素症候群",
    termEn: "Serotonin syndrome",
    category: "pharmacology",
    definition: "血清素活性過高造成的潛在急症，特徵可含自主神經不穩、神經肌肉過動與心智狀態改變。",
    related: ["ssri", "ddi"],
  },
  {
    slug: "eps",
    termZh: "錐體外徑症狀",
    termEn: "Extrapyramidal symptoms",
    abbr: "EPS",
    category: "pharmacology",
    definition: "與 D2 阻斷相關的運動不良反應，包括帕金森樣、急性肌張力不全、靜坐不能等。",
    related: ["d2", "nms"],
  },
  {
    slug: "nms",
    termZh: "神經阻斷劑惡性症候群",
    termEn: "Neuroleptic malignant syndrome",
    abbr: "NMS",
    category: "pharmacology",
    definition: "與多巴胺阻斷相關的罕見急症，可含高熱、肌僵、自主神經不穩與意識改變。",
    related: ["eps", "d2"],
  },
  {
    slug: "qtc",
    termZh: "QTc 間期",
    termEn: "QTc interval",
    category: "pharmacology",
    definition: "校正心率後的 QT，部分精神藥物可能延長，需結合電解質與其他危險因子評估。",
    related: ["ddi"],
  },
  {
    slug: "treatment-resistance",
    termZh: "治療阻抗",
    termEn: "Treatment resistance",
    category: "psychiatry",
    definition: "對足夠劑量與時程的適當試驗反應不足。定義因疾患而異，需先排除順從性與診斷問題。",
    related: ["tms", "clozapine"],
  },
  {
    slug: "clozapine",
    termZh: "氯氮平",
    termEn: "Clozapine",
    category: "pharmacology",
    definition: "對治療阻抗思覺失調症具特殊地位的多受體抗精神病藥，必須系統性血液與腸胃監測。",
    related: ["treatment-resistance", "d2"],
  },
  {
    slug: "tms",
    termZh: "經顱磁刺激",
    termEn: "Transcranial magnetic stimulation",
    abbr: "TMS",
    category: "neuroscience",
    definition: "以磁場在皮質誘導電流的非侵入性腦刺激，rTMS／iTBS 用於特定憂鬱情境。",
    related: ["itbs", "neuroplasticity"],
  },
  {
    slug: "itbs",
    termZh: "間歇 theta 爆發刺激",
    termEn: "Intermittent theta burst stimulation",
    abbr: "iTBS",
    category: "neuroscience",
    definition: "一種較短時間的 TMS 脈衝模式，常用於左側 DLPFC 相關憂鬱協議。",
    related: ["tms"],
  },
  {
    slug: "neurofeedback",
    termZh: "神經生理回饋",
    termEn: "Neurofeedback",
    category: "neuroscience",
    definition: "以即時腦訊號訓練自我調節的方法；協定異質，證據需依適應症個別評估。",
    related: ["neuroplasticity"],
  },
  {
    slug: "neuroplasticity",
    termZh: "神經可塑性",
    termEn: "Neuroplasticity",
    category: "neuroscience",
    definition: "神經系統依經驗改變結構與功能的能力，是學習、復健與許多治療效應的共同語言。",
    related: ["tms", "inhibitory-learning"],
  },
  {
    slug: "dmn",
    termZh: "默認模式網絡",
    termEn: "Default mode network",
    abbr: "DMN",
    category: "neuroscience",
    definition: "在心智漫遊與自我參照思考時較活躍的大腦網絡，任務需求下需被適當抑制。",
    related: ["attention", "rumination"],
  },
  {
    slug: "rumination",
    termZh: "反芻",
    termEn: "Rumination",
    category: "cognition",
    definition: "重複、抽象、以原因與後果打轉的思考，占用工作記憶並維持憂鬱與焦慮。",
    related: ["cognitive-triad", "dmn"],
  },
  {
    slug: "hpa",
    termZh: "下視丘—腦垂體—腎上腺軸",
    termEn: "Hypothalamic–pituitary–adrenal axis",
    abbr: "HPA",
    category: "neuroscience",
    definition: "壓力反應的內分泌軸，慢性活化與部分情感、創傷相關疾患的研究有關。",
    related: ["ptsd"],
  },
  {
    slug: "ptsd",
    termZh: "創傷後壓力症",
    termEn: "Post-traumatic stress disorder",
    abbr: "PTSD",
    category: "psychiatry",
    definition: "暴露於創傷事件後，以再體驗、迴避、認知情緒改變與高警覺等群聚呈現的疾患。",
    related: ["emdr", "hpa"],
  },
  {
    slug: "adhd",
    termZh: "注意力不足過動症",
    termEn: "Attention-deficit/hyperactivity disorder",
    abbr: "ADHD",
    category: "psychiatry",
    definition: "以注意力、衝動與過動／內在躁動為核心的神經發展疾患，成人期常以執行功能困難呈現。",
    related: ["executive-function", "neurodiversity"],
  },
  {
    slug: "effect-size",
    termZh: "效果量",
    termEn: "Effect size",
    category: "methods",
    definition: "描述介入效應大小的統計量（如 Cohen's d、Hedges' g），閱讀文獻時應與信賴區間一起看。",
    related: ["rct", "systematic-review"],
  },
  {
    slug: "rct",
    termZh: "隨機對照試驗",
    termEn: "Randomized controlled trial",
    abbr: "RCT",
    category: "methods",
    definition: "以隨機分派比較介入的試驗設計，是療效推論的重要來源，但仍受樣本與忠誠度限制。",
    related: ["effect-size", "systematic-review"],
  },
  {
    slug: "systematic-review",
    termZh: "系統性回顧",
    termEn: "Systematic review",
    category: "methods",
    definition: "以預先設定方法搜尋與合成研究的文獻形式；若進行統計合成則為統合分析。",
    related: ["rct", "effect-size"],
  },
  {
    slug: "informed-consent",
    termZh: "知情同意",
    termEn: "Informed consent",
    category: "methods",
    definition: "在理解益處、風險、替代方案與拒絕權利後做成的治療決定，應隨病程再確認。",
    related: ["case-formulation"],
  },
];
